### ISSUE TITLE
What conference or journal did this paper submit to and when will the code release?

### ISSUE THREAD

**Issue by Cc19245** [MISTLab/Swarm-SLAM#1]
Hi, @lajoiepy! Thanks for your great work!

I'd like to know what conference or journal did this paper submit to? And when will the code release?

**Comment by lajoiepy** [comment]
Hi! Thanks for your interest! 

The code is already public, use this repo as a ROS 2 workspace and clone the sub-repos using vcs as described in our start-up instructions: https://lajoiepy.github.io/cslam_documentation/html/md_startup-instructions.html

The Swarm-SLAM stack includes 4 packages:
- [cslam](https://github.com/lajoiepy/cslam): contains the Swarm-SLAM nodes;
- [cslam_interfaces](https://github.com/lajoiepy/cslam_interfaces): contains the custom ROS 2 messages;
- [cslam_experiments](https://github.com/lajoiepy/cslam_experiments): contains examples of launch files and configurations for different setups;
- [cslam_visualization](https://github.com/lajoiepy/cslam_visualization): contains an online (optional) visualization tool to run on your base station to monitor the mapping progress.

I'll let you know the journal it is submitted to once the paper is accepted!

Cheers!

**Comment by lajoiepy** [comment]
In the mean time, here is a link to our paper on arXiv: https://arxiv.org/abs/2301.06230

**Comment by lajoiepy** [comment]
To get the code:
```
sudo apt install python3-vcstool
git clone https://github.com/MISTLab/Swarm-SLAM.git
cd Swarm-SLAM
mkdir src
vcs import src < cslam.repos
```

**Comment by Cc19245** [comment]
> 

Great! Thanks a lot!
