### ISSUE TITLE
Need a case

### ISSUE THREAD

**Issue by TwiceMao** [MISTLab/Swarm-SLAM#10]
Could you please provide a case? The configuration and steps to run your code on a certain dataset? Including data directory settings and instructions.

**Comment by lajoiepy** [comment]
The launch files used for the dataset experiments: https://github.com/lajoiepy/cslam_experiments/tree/main/launch/datasets_experiments

They launch everything including the ros2 bags. Look into the code to see where to place them. I suggest using the Graco dataset which is already provided in the ros2 format:   https://sites.google.com/view/graco-dataset/download
