### ISSUE TITLE
How to save the estimated pose result to the local path? How to save it locally?

### ISSUE THREAD

**Issue by TwiceMao** [MISTLab/Swarm-SLAM#12]
How to save the estimated pose result to the local path? How to save it locally?

**Comment by lajoiepy** [comment]
By enabling the logs, you will get the resulting pose graph in your log_folder https://github.com/lajoiepy/cslam_experiments/blob/9f72df6549478e55643e5c1ae566675d14faee13/config/graco_lidar.yaml#L35
For online visualization of the pose graph, you can run https://github.com/lajoiepy/cslam_visualization
