### ISSUE TITLE
Depth Scale

### ISSUE THREAD

**Issue by TwiceMao** [MISTLab/Swarm-SLAM#15]
I use my own custom dataset, the depth scale of the depth map is different from the existing data sets, how to modify this correspondingly in the code?

**Comment by lajoiepy** [comment]
The processing of depth images is done [in this file](https://github.com/lajoiepy/cslam/blob/1a7b73245460b990288daaae200fe30fcdfbdd8e/src/front_end/rgbd_handler.cpp). 

So I suggest that you modify it according to you specific depth data. If need be, you should be able to write your own custom handler by following the same template as this file.
