### ISSUE TITLE
/cslam_experimetns/config/renderzvous/.config

### ISSUE THREAD

**Issue by TwiceMao** [MISTLab/Swarm-SLAM#16]
What is the meaning of .config in the /cslam_experimetns/config/renderzvous/.config directory? Because I am using my own custom data set now, I don't know how to write the corresponding .config file

**Comment by lajoiepy** [comment]
The goal of those file, like this [one](https://github.com/lajoiepy/cslam_experiments/blob/main/config/rendezvous/kitti09_5robots_rdv.config), is to specify fake rendezvous when running datasets to test the behavior of Swarm-SLAM under non-continuous communication.
The format is the following:
ROBOT_ID, START_0, END_0, START_1,END_1, ...
where start and end define the time intervals (after launch) during which the robot is considered in communication range. 

This is an optional config, you can simply disable this function like [here](https://github.com/lajoiepy/cslam_experiments/blob/9f72df6549478e55643e5c1ae566675d14faee13/launch/datasets_experiments/kitti360_stereo.launch.py#L145)
