### ISSUE TITLE
PGO is not working properly on custom dataset

### ISSUE THREAD

**Issue by TwiceMao** [MISTLab/Swarm-SLAM#17]
I tried to modify the launch and yaml files, based on rtabmap_rgbd_odometry.launch and cslam_rgbd.launch.py. Use custom RGBD to Ros bag2 file. It looks like rgbd_odometry works, but strangely, pose graph optimization doesn't.

![image](https://github.com/MISTLab/Swarm-SLAM/assets/43490149/ef1618ae-f7f4-4eef-a8ac-0abfbafab463)

![image](https://github.com/MISTLab/Swarm-SLAM/assets/43490149/5cd99916-a35c-490a-af6f-6efc48afaa92)

![image](https://github.com/MISTLab/Swarm-SLAM/assets/43490149/f1bde2a1-2325-4731-bef9-ad45006bcb3e)

**Comment by lajoiepy** [comment]
Can you give more details? Why do you think the pose graph optimization doesn't work? 
I suggest using `rqt_graph` to visualize the nodes and topics. Chez if they are all connected. Then use `ros2 topic hz` or `ros2 topic echo` or `ros2 node info` to check if all the topics are publishing.

**Comment by lajoiepy** [comment]
I am sorry that your are facing challenges running our code.

I strongly suggest to first focus on odometry, without launching Swarm-SLAM. Swarm-SLAM needs, as input, a stable 
 and reasonably accurate odometry to work. The examples we provide leverage RTAB-Map for odometry, but I suggest trying other odometry softwares if this one does not work.
 
 Once you have odometry working properly with your dataset, you could then try to run Swarm-SLAM.

**Comment by TwiceMao** [comment]
Thx ！！！
&nbsp;


毛懋
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Pierre-Yves ***@***.***&gt;; 
发送时间: 2023年5月29日(星期一) 上午6:59
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [MISTLab/Swarm-SLAM] PGO is not working properly on custom dataset (Issue #17)





 
I am sorry that your are facing challenges running our code.
 
I strongly suggest to first focus on odometry, without launching Swarm-SLAM. Swarm-SLAM needs, as input, a stable
 and reasonably accurate odometry to work. The examples we provide leverage RTAB-Map for odometry, but I suggest trying other odometry softwares if this one does not work.
 
Once you have odometry working properly with your dataset, you could then try to run Swarm-SLAM.

**Comment by TwiceMao** [comment]
@lajoiepy  Now rtabmap odometry works fine. But it seems that there is still a problem. The odometry stops after running, and there is no follow-up response. There is nothing using cslam_visualization. Set the 'enable_logs' variable to true in the yaml file, and no data is saved locally.
![image](https://github.com/MISTLab/Swarm-SLAM/assets/43490149/692f18a7-91bb-48b0-aecd-da054f10794d)
![image](https://github.com/MISTLab/Swarm-SLAM/assets/43490149/738c9db7-feea-4bb8-82a5-8d4e206b69c7)
![image](https://github.com/MISTLab/Swarm-SLAM/assets/43490149/5ef76e98-1ca7-4946-81e0-e0e4eecec93d)

**Comment by TwiceMao** [comment]
@lajoiepy 
Now use the following topics: rgb_topic, depth_topic, camera_info_topic.
![image](https://github.com/MISTLab/Swarm-SLAM/assets/43490149/a269a954-221f-4c8c-b357-27bbd5cd6a9e)
But I saw your document that the topic of cslam is left_image_topic, right_image_topic, left_camera_info_topic, right_camera_info_topic, etc.
![YRF6`YJF{WK795XD~2(X~YR](https://github.com/MISTLab/Swarm-SLAM/assets/43490149/d61eb42c-1a71-4b17-860c-203edcd97c6b)
So I wonder if this will be a problem.
