### ISSUE TITLE
After Odometry can run, PGO still can't run normally

### ISSUE THREAD

**Issue by TwiceMao** [MISTLab/Swarm-SLAM#19]
@lajoiepy  Now rtabmap odometry works fine. But it seems that there is still a problem. The odometry stops after running, and there is no follow-up response. There is nothing using cslam_visualization. Set the 'enable_logs' variable to true in the yaml file, and no data is saved locally.
![image](https://github.com/MISTLab/Swarm-SLAM/assets/43490149/692f18a7-91bb-48b0-aecd-da054f10794d)
![image](https://github.com/MISTLab/Swarm-SLAM/assets/43490149/738c9db7-feea-4bb8-82a5-8d4e206b69c7)
![image](https://github.com/MISTLab/Swarm-SLAM/assets/43490149/5ef76e98-1ca7-4946-81e0-e0e4eecec93d)

**Comment by TwiceMao** [comment]
@lajoiepy 
Now use the following topics: rgb_topic, depth_topic, camera_info_topic.
![YRF6`YJF{WK795XD~2(X~YR](https://github.com/MISTLab/Swarm-SLAM/assets/43490149/d61eb42c-1a71-4b17-860c-203edcd97c6b)

But I saw your document that the topic of cslam is left_image_topic, right_image_topic, left_camera_info_topic, right_camera_info_topic, etc.
![image](https://github.com/MISTLab/Swarm-SLAM/assets/43490149/a269a954-221f-4c8c-b357-27bbd5cd6a9e)
So I wonder if this will be a problem.

**Comment by lajoiepy** [comment]
Hi!

- To double-check the odometry, I suggest that you visualize it in rviz. Launch `rviz2`, click on `Add` and select your odometry by topic, then make sure to set the correct fixedframe under Gloval Options. You then should be able to visualize the odometry output and figure out if it is correct.

- left and right topics are for stereo cameras. Look here for config examples for [stereo](https://github.com/lajoiepy/cslam_experiments/blob/main/config/kitti_stereo.yaml), [rgbd](https://github.com/lajoiepy/cslam_experiments/blob/main/config/realsense_rgbd.yaml), or [lidar](https://github.com/lajoiepy/cslam_experiments/blob/main/config/kitti_lidar.yaml)

- Finally, make sure that all the topics are well connected, i.e. that Swarm-SLAM subscribes to the correct topics. `rqt_graph` should help you to figure this out.

**Comment by TwiceMao** [comment]
![image](https://github.com/MISTLab/Swarm-SLAM/assets/43490149/9225c067-5796-43c8-bb19-1a2a11e1c136)
![image](https://github.com/MISTLab/Swarm-SLAM/assets/43490149/57e42023-1416-4578-81af-03caf5d3cb44)


![image](https://github.com/MISTLab/Swarm-SLAM/assets/43490149/c974e07a-6ab3-498f-864f-36d0e6a484e9)

![image](https://github.com/MISTLab/Swarm-SLAM/assets/43490149/ef55d62f-b9eb-4d01-912b-87bea1e9ae62)

![image](https://github.com/MISTLab/Swarm-SLAM/assets/43490149/f71074c4-9785-4406-8e76-9d42448b74d6)

**Comment by TwiceMao** [comment]
@lajoiepy 
Now use Swram-SLAM to run through the RGBD dataset. But our purpose is to calculate the error between the estimated pose and the true pose. How can I find the correspondence between the estimated pose and the true pose?
My data set has 2 robots, but in the results folder, only the robot numbered 0 contains initial_global_pose_graph.g2o and optimized_global_pose_graph.g2o files, and the robot numbered 1 does not have these two files, but there are log.csv and pose_timestamps1.csv two empty files.
Image of rviz visualization
![image](https://github.com/MISTLab/Swarm-SLAM/assets/43490149/a046bcf1-fac9-4282-ae99-ddc2f101ef7b)

**The files in the results folder corresponding to the robot numbered 1**
![image](https://github.com/MISTLab/Swarm-SLAM/assets/43490149/ba5b4eb8-d601-4004-9c5b-a97a62e3a32d)
![image](https://github.com/MISTLab/Swarm-SLAM/assets/43490149/2bf54e6c-b6f4-4c1a-8601-77c00df9ee1a)

The files in the results folder corresponding to the robot numbered 0
![image](https://github.com/MISTLab/Swarm-SLAM/assets/43490149/05b63ed5-9793-4495-be7c-b7f73fbbd6f9)

**Comment by lajoiepy** [comment]
It's great to see your progress!
In the optimized pose graph file, the long number after VERTEX_SE3:QUAT is a gtsam::LabeledSymbol::key corresponding to a pose of a robot. You can see here how to retrieve the robot and pose ids for each key: https://github.com/lajoiepy/cslam/blob/1a7b73245460b990288daaae200fe30fcdfbdd8e/src/back_end/gtsam_utils.cpp#L44

Then, as you pointed out, the evaluation currently works only with GPS positions, so you will need to figure out how to associate each of your 6DOF GT poses with the estimated poses (probably using the timestamps).

**Comment by TwiceMao** [comment]
Regarding the optimized pose graph file, you can see [writeg2o](https://github.com/lajoiepy/cslam/blob/1a7b73245460b990288daaae200fe30fcdfbdd8e/src/back_end/decentralized_pgo.cpp#L326 )from the code here, because you are using the GTSAM::writeg2o function written to local, but that meaning doesn't seem to have anything to do with timestamps. This caused me a lot of trouble aligning the estimated pose with the GT pose. I'm curious how the ATE data on your paper aligns with gps and gt.

**Comment by TwiceMao** [comment]
I should have successfully run the Swarm-SLAM method on the RGBD dataset and calculated the associated ATE with EVO.
For a 2-room scene

Visualization results of rviz of Swarm-SLAM:
![apart_1_1](https://github.com/MISTLab/Swarm-SLAM/assets/43490149/4354bc89-3989-49ae-8ba4-996c0d722d3a)
![apart_1_2](https://github.com/MISTLab/Swarm-SLAM/assets/43490149/85afb270-b84e-4818-b765-7df449d99f02)

Visualization Results Measured Using the EVO Tool
![0_align_orign](https://github.com/MISTLab/Swarm-SLAM/assets/43490149/1dfeb530-7726-4aec-b4b7-3e35424c22b2)
![1_align_orign](https://github.com/MISTLab/Swarm-SLAM/assets/43490149/de1b40e4-e4b3-48d2-b54c-94526f254815)

Thank you for your patience and reply~Thank you again!

**Comment by lajoiepy** [comment]
Awesome! :D

**Comment by ResearcherYan** [comment]
@TwiceMao Hello, TwiceMao! Excuse me for disturbing you again. Could you please show the way how you visualize your point cloud as well as trajectories shown above? Since I have absolutely no idea how to do that using Swarm-SLAM. Thank you again!

**Comment by TakShimoda** [comment]
Hello @TwiceMao, I'm in the same boat as you, where I have ground-truth data as timestamped 6DoF poses with no GPS data. How did you manage to evaluate the estimated poses from g2o with evo? As mentioned in this issue, there's no unix timestamp associated with g2o files and we need some correspondence between ground-truth and estimated poses to align with Umeyama's method.
