### ISSUE TITLE
cslam: Cannot locate rosdep definition for [rtabmap]

### ISSUE THREAD

**Issue by rocker12121** [MISTLab/Swarm-SLAM#20]
Hello.

I successfully install all the dependencies. But when I run "rosdep install --from-paths src -y --ignore-src --rosdistro foxy", i get this error:

ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
cslam: Cannot locate rosdep definition for [rtabmap]

Can you tell me why it shows this error.
Note: I have already build rtabmap in my home/Downloads folder.

**Comment by Mahdikhoorishandiz** [comment]
Hello. 
I have the same problem, can you help me how to fix it?

**Comment by rocker12121** [comment]
hello.
try including "--include-eol-distros" at the end of the rosdep update command.
