### ISSUE TITLE
Issue about the data experiments using kitti360

### ISSUE THREAD

**Issue by DioBakery** [MISTLab/Swarm-SLAM#23]
The kitti360 structure is like this, I have also established the corresponding folder, how to use the 09 sequence for experiments?

<img width="373" alt="Snipaste_2023-09-26_10-07-59" src="https://github.com/MISTLab/Swarm-SLAM/assets/69229972/135cb7b0-4f06-4c36-b674-e9bfa0cfa2ff">

<img width="453" alt="Snipaste_2023-09-26_10-05-18" src="https://github.com/MISTLab/Swarm-SLAM/assets/69229972/a81de3b5-2b76-4c8e-8cf9-6cbf7c70d771">

**Comment by lajoiepy** [comment]
Sorry for the very late reply, I was on an internship and had no time for support. 

Please adapt the launch files to your systems paths.
For the bag files of KITTI360, you can specify it here: https://github.com/lajoiepy/cslam_experiments/blob/9f72df6549478e55643e5c1ae566675d14faee13/launch/datasets_experiments/kitti360_lidar.launch.py#L53

It is worth the time to carefully read the launch files to make sure they match your system installation, and were you store your bag/data.
