### ISSUE TITLE
set-up error

### ISSUE THREAD

**Issue by HaynesLi** [MISTLab/Swarm-SLAM#25]
Did anyone met these problems while setting up.

ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
cslam: Cannot locate rosdep definition for [perception_pcl]
cslam_common_interfaces: Cannot locate rosdep definition for [rtabmap_msgs]

**Comment by asadwadood** [comment]
Hello, i think you are getting this error while using " rosdep update" command.

try to use "rosdep update --include-eol-distros"
hope this will solve your error.

**Comment by asadwadood** [comment]
in my case i used Ros2, foxy, Ubuntu 20. and i didn't installed rtabmap manually. you only need to install gtsam manually

**Comment by asadwadood** [comment]
i have used below two commands to remove these errors
rosdep update --include-eol-distros
rosdep install --from-paths src -y --ignore-src --rosdistro foxy
