### ISSUE TITLE
Error while performing setup 

### ISSUE THREAD

**Issue by aryanthakur0600** [MISTLab/Swarm-SLAM#26]
System : jetson nano
Ubuntu 18 jetpack 4.5.1
(Can't be changed)

I am using a ros2foxy container for this. Here is how I went about it .
Cloned the swarm slam and created a workspace with src folder inside it and performed the import of cslam.repos inside the src.
Created a archiconda environment named cslam of python 3.8 and ran pip install -r /swarm -slam/requirements.txt .
Inside the cslam virtual environment installed gtsam ran the check-out command and went through with the installation.build was successful.
After this I went back outside the conda environment and ran the rest of the commands

When I ran :

rosdep update
rosdep install --from-paths src -y --ignore-src --rosdistro foxy

I got error : ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
cslam: Cannot locate rosdep definition for [perception_pcl]
cslam_common_interfaces: Cannot locate rosdep definition for [rtabmap_msgs]
but there was a message below it saying all necessary packages installed. I did try the rosdep update --include-eol-distros but it didn't work.

So then I activated the conda cslam went to ws and ran colcon build and it gave error.

Any help will be appreciated sorry for the length just wanted to give the whole picture.

**Comment by clean-shero** [comment]
> I suggest you change to Ubuntu20.04 and Ros2-Foxy , and then it should work.
> 
> To be honest, I spent one and a half months processing these codes but still not done. The document is insufficient for me.

May I ask if you have successfully installed it

My environment is Ubuntu20.04 and Ros2-Foxy ，But it still failed

**Comment by lajoiepy** [comment]
Sorry for the very late reply, I was on an internship and had no time for support. I fixed the build for Ubuntu 22.04+ROS 2 Humble (just follow the run procedures here: https://github.com/MISTLab/Swarm-SLAM/blob/main/.github/workflows/main.yml)
