### ISSUE TITLE
Robot IDs must start at 0

### ISSUE THREAD

**Issue by mjforan** [MISTLab/Swarm-SLAM#34]
In `neighbors_manager.py` `check_neighbors_in_range` loops through `range(self.max_nb_robots)` and checks which neighbors are in range. This breaks if the robot ID is greater than `max_nb_robots`. You should add a check or at least a note in the documentation saying that robot IDs must start at 0 and not be greater than `max_nb_robots`.

**Comment by lajoiepy** [comment]
Thanks for pointing this out! I added it to the documentation.
