### ISSUE TITLE
Real-time problem & trajectory problem on Graco dataset

### ISSUE THREAD

**Issue by ResearcherYan** [MISTLab/Swarm-SLAM#35]
## Real-time problem
As I mentioned in [issue #31](https://github.com/MISTLab/Swarm-SLAM/issues/31#issuecomment-2022899463), my personal computer couldn't handle the computation burden of the algorithm. So I deployed the docker container on a server, with 2 AMD EPYC 9174F CPUs. 

However, I found the algorithm still can't run in real time. The odometry ran only at around 2Hz when no loop closure was involved, while all the 64 CPU cores were running almost at max capacity.

![2024-03-29_16-02](https://github.com/MISTLab/Swarm-SLAM/assets/46956622/b84468b5-cabd-4490-beb7-8348d4e7f2cd)
![2024-03-29_16-01](https://github.com/MISTLab/Swarm-SLAM/assets/46956622/1d4bf99e-4370-4975-9f56-5fc0734d5f1c)

Since the CPU on that server is strong enough, I'd like to know if your code is so computation-demanding or if I did some wrong setups that led to this real-time problem.

## Trajectory problem
Nevertheless, running on the server side does make the trajectory more reasonable. It's more continuous compared to my PC running result. Yet the trajectories are still not on the same plane.

![2024-03-29_16-25](https://github.com/MISTLab/Swarm-SLAM/assets/46956622/6194e6cf-7a10-499c-b77e-7b5cb617237f)
![2024-03-29_16-28](https://github.com/MISTLab/Swarm-SLAM/assets/46956622/4940c1e3-828f-4d91-8301-556e9ccb2d85)

I'd like to know if your experiment results on Graco are the same or if my trajectories are wrong.

Thanks a lot.

**Comment by mjforan** [comment]
The resource hog is rtabmap's `icp_odometry`. In my preliminary testing FAST-LIO2 is an order of magnitude faster and provides accurate odometry.

**Comment by ResearcherYan** [comment]
I'll try a new odometry later. Thx!
