### ISSUE TITLE
voxel_size is too small

### ISSUE THREAD

**Issue by Yyote** [MISTLab/Swarm-SLAM#36]
I have a problem using Swarm-SLAM with a 2d lidar. I'm launching the experiment_lidar.launch.py with commented out zenoh in a custom launch file with a custom simulator. The lidar gives 120 points around the robot. I managed to launch the algorithms but I get the following error:

```
[Open3D Error] (std::shared_ptr<open3d::geometry::PointCloud> open3d::geometry::PointCloud::VoxelDownSample(double) const) /root/Open3D/cpp/open3d/geometry/PointCloud.cpp:366: voxel_size is too small.
``` 

I tried varying the voxel_size from 0.1 to 1000 and it made no difference. Any help would be appreciated.

**Comment by lajoiepy** [comment]
Swarm-SLAM does not support 2D lidars at the moment. 
There are some pointers here : https://github.com/lajoiepy/cslam_experiments/issues/8
However, 2D inter-robot loop closure detection is difficult considering the small amount of information the sensor outputs.
