### ISSUE TITLE
Test Dataset

### ISSUE THREAD

**Issue by BamsaAhmed** [MISTLab/Swarm-SLAM#4]
I used kittidata seq 07 to evaulate the system by splitting it, but i don't know how to compare split parts with ground truth, should i split the ground truth data also? and how?

**Comment by lajoiepy** [comment]
Hi, thanks for your interest in Swarm-SLAM! 
First your bag needs to contain GPS data and you should enable GPS logging like in here: https://github.com/lajoiepy/cslam_experiments/blob/d1c7d277786bc7a5df2898e55f088d0e16d53ee0/config/kitti_lidar.yaml#L37
GPS files should be generated when you run the stack (see: https://github.com/lajoiepy/cslam/blob/fd62c32e44c736c79b991c7d2d595766956313e9/src/back_end/utils/logger.cpp#L155 )
Then you can use the synchronized GPS files to evaluate the resulting pose graphs.
