### ISSUE TITLE
[launch_ros.actions.load_composable_nodes]: Failed to load node 'rectify_color_node' of type 'image_proc::RectifyNode' in container '/r/image_proc_container': Could not find requested resource in ament index

### ISSUE THREAD

**Issue by gghybyv** [MISTLab/Swarm-SLAM#42]
Errors happen on dataset s3e_colloge

**Comment by lajoiepy** [comment]
It seems like some package is missing, or the installation is broken.
Can you give more details? such as your system version and the full error output?
