### ISSUE TITLE
No Loop Closure Happening

### ISSUE THREAD

**Issue by saadmahboob71** [MISTLab/Swarm-SLAM#49]
Hi, I am trying to run Swarm SLAM on real robot/s. So I connected realsense camera D435I and changed the real_senses file to run rs_launch instead of multi launch one and modified it to run the device D435i it runs succesfully. 

I am getting data on camera/color/image_raw but not on r0/color/image_raw

But after Initilization Done which is printed by clsam_map_manager after initilization of map manager, camera and loop closure detection I don't see any data coming through. I looked into the code cslam loop closure detection is waiting for a neighbor to join and then update itself but I was looking at the internal loop closure the issue is that there is nothing being published on the keyframe topic. What am I missing ? 

The screenshot is attached for your kind reference.  
![Screenshot from 2024-08-11 15-10-27](https://github.com/user-attachments/assets/67e60265-3979-4fcf-b0f7-7c69a1d998ce)
![Screenshot from 2024-08-11 15-15-16](https://github.com/user-attachments/assets/6a0c2021-f28e-4d95-a378-0f053039c7c1)

Appreciate your help. Thanks

**Comment by lajoiepy** [comment]
Hi! This is a probably a topic settings issues. You need to make sure that the topics published by your sensor match the ones expected by Swarm-SLAM (or you could modify our code to match your sensor). For that you will need to remap some topics as explained [here](https://answers.ros.org/question/376720/how-to-remap-topic-in-a-ros2-launch-file/).

**Comment by lajoiepy** [comment]
You need depth data as well. So make sure your camera correctly publishes it

**Comment by saadmahboob71** [comment]
Thanks my camera is publishing it able to run the file and make it go inside the inter loop closure but the issue I am having now is first of all, is there a way to save the built map ?

Secondly I was trying to visualize the map but not being able to do so I ran the visualization named realsense_visualization.launch.py it goes in the callback but says 0 point cloud recieved launches rviz but not able to visualize anything but when I echo the topic /cslam/viz/keyframe_pointcloud I am recieving data.

**Comment by lajoiepy** [comment]
You have the pose graph in the logs. If you want to save a visualization of the map, I suggest using rerun. To do so, look at this branch https://github.com/lajoiepy/cslam_visualization/tree/rerun_viz

**Comment by saadmahboob71** [comment]
Thanks for your prompt responses and the help with this along the way. So i have been trying to run the examples of garco dataset. When I launch 1 robot it works fine I get the loop closures and can also visualize the pointclouds using rviz but as soon as I make it to two it gives me the error first about bundle adjustment not being used and secondly whenever it goes some data it says about ignoring due to tf being out of date. I checked my data time for tf of velodyne for both robots is more or less the same it works fine for 1 but as soon as you add another it starts logging this error for the second one. I swapped both trajectories i.e 1 with 2 same issue as soon as it launches the second one it starts logging this error, screenshot is attached for your kind reference. 

![Screenshot from 2024-09-09 21-42-34](https://github.com/user-attachments/assets/381f1d4b-00d7-4a27-a469-8e97eeed14d0)

**Comment by lajoiepy** [comment]
This is a RTAB-Map error, I suggest looking their forums for a solution.
Another suggestion is to use another lidar odometry software. I recommend https://github.com/hku-mars/FAST_LIO

**Comment by saadmahboob71** [comment]
Do u have an example to use it? Should I just change the replace RTAB-MAP node in the garco_lidar.py file with a Fast_LIO one ??

**Comment by lajoiepy** [comment]
Yes.
For FAST-LIO on GRACO try this config
```
/**:
    ros__parameters:
        feature_extract_enable: false
        point_filter_num: 4
        max_iteration: 3
        filter_size_surf: 0.5
        filter_size_map: 0.5
        cube_side_length: 1000.0
        runtime_pos_log_enable: false
        map_file_path: "./test.pcd"

        common:
            lid_topic:  "/velodyne/points"
            imu_topic:  "/gnss/imu"
            time_sync_en: false         # ONLY turn on when external time synchronization is really not possible
            time_offset_lidar_to_imu: 0.0 # Time offset between lidar and IMU calibrated by other algorithms, e.g. LI-Init (can be found in README).
                                        # This param will take effect no matter what time_sync_en is. So if the time offset is not known exactly, please set as 0.0

        preprocess:
            lidar_type: 2                # 1 for Livox serials LiDAR, 2 for Velodyne LiDAR, 3 for ouster LiDAR, 
            scan_line: 16
            scan_rate: 10                # only need to be set for velodyne, unit: Hz,
            timestamp_unit: 2            # the unit of time/t field in the PointCloud2 rostopic: 0-second, 1-milisecond, 2-microsecond, 3-nanosecond.
            blind: 2.0

        mapping:
            acc_cov: 0.1
            gyr_cov: 0.1
            b_acc_cov: 0.0001
            b_gyr_cov: 0.0001
            fov_degree:    360.0
            det_range:     100.0
            extrinsic_est_en:  false      # true: enable the online estimation of IMU-LiDAR extrinsic,
            extrinsic_T: [ 0.0126906, 0.0207969, -0.122356]
            extrinsic_R: [ 0.99991641, -0.01025064, -0.00787932, 
                        0.01018984,  0.9999183,  -0.00771833 , 
                        0.00795779,  0.0076374,   0.99993917]

        publish:
            path_en:  true
            scan_publish_en:  false       # false: close all the point cloud output
            dense_publish_en: false       # false: low down the points number in a global-frame point clouds scan.
            scan_bodyframe_pub_en: false  # true: output the point cloud scans in IMU-body-frame

        pcd_save:
            pcd_save_en: false
            interval: -1                 # how many LiDAR frames saved in each pcd file; 
                                        # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.
```

and this launch file:
```
import os.path

from ament_index_python.packages import get_package_share_directory

from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument
from launch.substitutions import LaunchConfiguration, PathJoinSubstitution
from launch.conditions import IfCondition

from launch_ros.actions import Node


def generate_launch_description():
    package_path = get_package_share_directory('fast_lio')
    default_config_path = os.path.join(package_path, 'config')
    default_rviz_config_path = os.path.join(
        package_path, 'rviz', 'fastlio.rviz')

    use_sim_time = LaunchConfiguration('use_sim_time')
    config_path = LaunchConfiguration('config_path')
    config_file = LaunchConfiguration('config_file')
    rviz_use = LaunchConfiguration('rviz')
    rviz_cfg = LaunchConfiguration('rviz_cfg')

    declare_use_sim_time_cmd = DeclareLaunchArgument(
        'use_sim_time', default_value='false',
        description='Use simulation (Gazebo) clock if true'
    )
    declare_config_path_cmd = DeclareLaunchArgument(
        'config_path', default_value=default_config_path,
        description='Yaml config file path'
    )
    decalre_config_file_cmd = DeclareLaunchArgument(
        'config_file', default_value='velodyne.yaml',
        description='Config file'
    )
    declare_rviz_cmd = DeclareLaunchArgument(
        'rviz', default_value='false',
        description='Use RViz to monitor results'
    )
    declare_rviz_config_path_cmd = DeclareLaunchArgument(
        'rviz_cfg', default_value=default_rviz_config_path,
        description='RViz config file path'
    )

    fast_lio_node = Node(
        package='fast_lio',
        executable='fastlio_mapping',
        parameters=[PathJoinSubstitution([config_path, config_file]),
                    {'use_sim_time': use_sim_time}],
        output='screen',
        remappings=[
            ('/Odometry', '/odom'),
        ]
    )
    rviz_node = Node(
        package='rviz2',
        executable='rviz2',
        arguments=['-d', rviz_cfg],
        condition=IfCondition(rviz_use)
    )

    ld = LaunchDescription()
    ld.add_action(declare_use_sim_time_cmd)
    ld.add_action(declare_config_path_cmd)
    ld.add_action(decalre_config_file_cmd)
    ld.add_action(declare_rviz_cmd)
    ld.add_action(declare_rviz_config_path_cmd)

    ld.add_action(fast_lio_node)
    ld.add_action(rviz_node)

    return ld
```

**Comment by lajoiepy** [comment]
RTAB-Map might be failing because your computer runs out out memory when you run multiple robots at once.

**Comment by saadmahboob71** [comment]
Thanks a lot for your prompt responses, will try this.
