### ISSUE TITLE
Availability of the real-world dataset and instructions on using it with Swarm-SLAM

### ISSUE THREAD

**Issue by Mechazo11** [MISTLab/Swarm-SLAM#50]
Hello @lajoiepy 

Thank you very much for publicly sharing the codes for SlideSLAM. It is an excellent CSLAM system.

I am also working on a similar CSLAM system and am interested in testing my work with your novel framework. In this regard is the dataset publicly available and secondly are the instructions to run this dataset with your CSLAM framework available?

Thank you for your time.

With best,
@Mechazo11

**Comment by lajoiepy** [comment]
The datasets I used are publicly available. For example GRACO https://sites.google.com/view/graco-dataset or S3E https://paperswithcode.com/dataset/s3e

Some launch files to test them are in the cslam_experiments package https://github.com/lajoiepy/cslam_experiments

As for the online demo/deployment shown in the paper, the raw data was not recorded, so there is no dataset for that experiment.

**Comment by Mechazo11** [comment]
Thank you very much @lajoiepy for pointing me to the GRACO dataset and providing information regarding the real-world dataset.

With best,
@Mechazo11
