### ISSUE TITLE
Package 'cslam_experiments' not found: "package 'cslam_experiments' not found, searching: ['/opt/ros/foxy']"

### ISSUE THREAD

**Issue by illuosion** [MISTLab/Swarm-SLAM#6]
What should I do if this problem occurs?

**Comment by lajoiepy** [comment]
This indicates that the launch is only looking in the ROS 2 path for packages `/opt/ros/foxy`. However, after building, the Swarm-SLAM packages will be in the install folder of the workspace.

TL;DR: You need to source your workspace before launching:
```
cd your_ros2_worskspace
source install/setup.bash
```
