### ISSUE TITLE
hello,I follow your guide 'source install/setup.bash',but I still got the problem below.

### ISSUE THREAD

**Issue by illuosion** [MISTLab/Swarm-SLAM#8]

**Comment by illuosion** [comment]
<img width="847" alt="屏幕截图 2023-04-18 220926" src="https://user-images.githubusercontent.com/63509752/232804013-f756f76e-edc9-45ca-ab17-c8a422c927ba.png">

**Comment by illuosion** [comment]
Sorry to interrupt, but I am trapped in this problem and I am not quite familiar with ROS2

**Comment by lajoiepy** [comment]
Ok, this is definitely a ROS 2 issue.
The ROS 2 discord, forum, etc. might be able to help you.

That being said, I find it very odd that you created your workspace inside `/opt/ros/foxy`. Try creating your workspace somewhere else on your machine, e.g. `/home/username/Documents`.

**Comment by illuosion** [comment]
yeah， If I want to launch the launch file like graco_lidar.launch.py,which command should I use?
