### ISSUE TITLE
An error when doing "colcon build"

### ISSUE THREAD

**Issue by TwiceMao** [MISTLab/Swarm-SLAM#9]
SwarmSLAM/build/cslam_common_interfaces/rosidl_generator_cpp/cslam_common_interfaces/msg/detail/local_image_descriptors__struct.hpp:19:10: fatal error: rtabmap_ros/msg/detail/rgbd_image__struct.hpp: No such file or directory
   19 | #include "rtabmap_ros/msg/detail/rgbd_image__struct.hpp"

![image](https://github.com/MISTLab/Swarm-SLAM/assets/43490149/17d12c0f-c833-4789-a81b-b11e1515b5c1)

![1683784554583](https://github.com/MISTLab/Swarm-SLAM/assets/43490149/b0ad6543-1df9-477b-a81a-10b92b15efea)

Could you help me？

**Comment by TwiceMao** [comment]
I have installed rtabmap by
sudo apt install ros-foxy-rtabmap-ros

**Comment by lajoiepy** [comment]
Thanks for pointing this out! 
There was a recent change in rtabmap_ros that seems to break things. I'll try to push a fix by next week.

In the mean time you can try the following:
- modify https://github.com/lajoiepy/cslam/blob/fd62c32e44c736c79b991c7d2d595766956313e9/include/cslam/front_end/rgbd_handler.h#LL6C23-L6C26 to `#include <rtabmap_msgs/msg/rgbd_image.hpp>`
- modify `rtabmap_ros` in https://github.com/lajoiepy/cslam_interfaces/blob/5a3f99aa84791d92293773f4aa3d2d56a4f3c232/cslam_common_interfaces/package.xml#L19 , https://github.com/lajoiepy/cslam_interfaces/blob/5a3f99aa84791d92293773f4aa3d2d56a4f3c232/cslam_common_interfaces/package.xml#L25 , https://github.com/lajoiepy/cslam_interfaces/blob/5a3f99aa84791d92293773f4aa3d2d56a4f3c232/cslam_common_interfaces/CMakeLists.txt#L40 , 
https://github.com/lajoiepy/cslam_interfaces/blob/5a3f99aa84791d92293773f4aa3d2d56a4f3c232/cslam_common_interfaces/CMakeLists.txt#L70 , and https://github.com/lajoiepy/cslam_interfaces/blob/5a3f99aa84791d92293773f4aa3d2d56a4f3c232/cslam_common_interfaces/msg/LocalImageDescriptors.msg#L7 to `rtabmap_msgs`

**Comment by TwiceMao** [comment]
@lajoiepy After doing what you said, the error is still reported. So I replaced the "rtabmap_ros" in all the files in the three directories /src/cslam, /src/cslam_experiments /src/cslam_interfaces with "rtabmap_msgs", and the "colcon build" command will not report an error. But there seems to be a problem when executing the "colco test" command, as shown in the figure
![image](https://github.com/MISTLab/Swarm-SLAM/assets/43490149/efaf9112-8f18-46d2-9850-5ca04f757f9e)

**Comment by lajoiepy** [comment]
You can use `colcon test-result --verbose` to get more info about the failed tests, but the only important tests are in the `cslam` package. Those have passed, so everything should be fine

**Comment by lajoiepy** [comment]
I fixed the rtabmap depencies. Please update your code :)
